version: "3.9"

services:
  spearphish:
    build: .
    container_name: spearphish-env
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    depends_on:
      - mailpit
      - mailpit2
  login-page:
    build:
      context: ./phishing_login
      ports:
        - "8081:80"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web inbox
  mailpit2:
    image: axllent/mailpit:latest
    container_name: mailpit2
    ports:
      - "1125:1025" # SMTP port
      - "8125:8025" # Private Web inbox for after log in
  
